# Docker Hub has a rich database of pre-built images that can be used
# Docker Hub: hub.docker.com

stages:
    - build
    - test
    - deploy

##################
# Assignment One #
##################

# Python

build_assignment_one:
    image: python 
    stage: build 
    script:
        - cd assignments/assignment_one/
        - 'python setup.py sdist bdist_wheel'
    artifacts:
        name: "${CI_PROJECT_NAME}_${CI_PIPELINE_ID}"
        paths:
            - dist/
        

test_assignment_one:
    image: python
    stage: test
    script:
        - cd assignments/assignment_one/
        - tox
    tags:
        - docker
    only:
        - master


# LaTeX

#pages:
#    image: datenstrom/debian-latex
#    stage: docs
#    script:
#        - apt-get --yes update && apt-get --yes install texlive-latex-extra
#        - apt-get --yes install build-essential
#        - pdflatex --version
#        - make -k
#    tags:
#        - docker
#    artifacts:
#        paths:
#        - public
