# Docker Hub has a rich database of pre-built images that can be used
# Docker Hub: hub.docker.com

stages:
    - build
    - test
    - deploy

cache:
    paths:
        - pelican/pdfs

##################
# Assignment One #
##################

# Python

build_assignment_one:
    image: python 
    stage: build 
    script:
        - cd assignments/assignment_one/
        - pip3 install -r requirements.txt
        - python3 setup.py sdist bdist_wheel
    artifacts:
        name: "${CI_PROJECT_NAME}_${CI_PIPELINE_ID}"
        paths:
            - assignments/assignment_one/dist/
    only:
        - master
        

test_assignment_one:
    image: python
    stage: test
    script:
        - cd assignments/assignment_one/
        - pip3 install tox
        - tox
    tags:
        - docker
    only:
        - master


# LaTeX

build_assignment_one_report:
    image: datenstrom/debian-latex
    stage: build
    script:
        - apt-get --yes update && apt-get --yes install texlive-latex-extra python-pygments
        - apt-get --yes install build-essential
        - pdflatex --version
        - cd assignments/assignment_one/docs/
        - make -k
    tags:
        - docker
    artifacts:
        paths:
            - assignments/assignment_one/docs/assignment_one.pdf
    only:
        - master
        - site


########
# Site #
########

pages:
    image: python:2
    stage: deploy
    script:
        - cd pelican/pelican-themes
        - git clone https://github.com/alexandrevicenzi/Flex.git
        - cd ../pelican-plugins
        - git clone https://github.com/getpelican/pelican-plugins.git
        - cd ../
        - pip -V
        - pip install -r requirements.txt
        - fab build                             # End Pelican
        - cd ../                                # Begin Jupyter Notebooks
        - apt-get --yes update && apt-get --yes install texlive
        - cat assignments/assignment_one/notebook-requirements.txt | xargs -n 1 -L 1 pip install
        - jupyter nbconvert --to html assignments/assignment_one/graph_structure/graph_structure.ipynb
        - mkdir -p public/notebooks/
        - cp assignments/assignment_one/graph_structure/graph_structure.html public/notebooks
    tags:
        - docker
    artifacts:
        paths:
            - public
    only:
        - master
        - site
